version: "3"
services:
  nacos:
    image: nacos/nacos-server:2.0.0-bugfix
    container_name: nacos-standalone
    environment:
      - MODE=standalone
      - NACOS_APPLICATION_PORT=8848
      - PREFER_HOST_MODE=hostname
      - NACOS_SERVER_IP=127.0.0.1
      - NACOS_SERVER_PORT=8848
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=127.00.1
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=local_nacos
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=123456
    env_file:
      - ./standalone.env
    volumes:
      - ./standalone-logs/:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
    networks:
      - nacos-network
    restart: always

networks:
  nacos-network:
    driver: bridge
